# src/main/resources/application-dev.yaml

spring:
  datasource:
    url: jdbc:h2:mem:taxi_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update  # Automatically creates/updates tables based on entity classes
    show-sql: true      # Show SQL queries in the console
  h2:
    console:
      enabled: true     # Enables the H2 console at /h2-console

logging:
  level:
    root: INFO
    org.springframework: DEBUG
